### PR TITLE
Changed some buttons into fab. Changed size of chart box

### PR DESCRIPTION
**Pull request by initfve**
Now everything seems fit into window size

### CODE REVIEW

**Comment by 13bscsaamjad** [comment]
the buttons for downloading still needs to be scrolled down. i am attaching a screenshot.
Screenshot 2020-09-28 at 10 34 18

**Comment by initfve** [comment]
That's weird. Buttons have set fixed position so they always be placed in left bottom corner. Are you sure that's not problem with cache or something like that?
obraz

**Comment by initfve** [comment]
Sorry, I know why this didn't work. I forget to include updated static file. Now app should works fine.

**Comment by 13bscsaamjad** [comment]
it still does not work for me :( can you please add the bundling in Dockerfile as well and remove it from repo?

**Comment by initfve** [comment]
I see source of problem. I didn't build entirie docker(because I would need setup Cassandra with proper database schema) I just was building frontend by webpack. 
I know why you don't see any changes. Line 29 in Dockerfile clone whole remote repo from github. I assume you use that in production because in development is useless. 
2 solutions come to my mind. First one, instead using remote repo just use local one (so don't clone, just copy files) or second one, test files in static dir and you will see changes

**Comment by 13bscsaamjad** [comment]
oh yeah, thanks for the tip, will test now :)

**Pull request merged**
